import { AuthLayout } from "@/layouts";
import { Typography } from "@/ui";
import Head from "next/head";

export default function Login() {
  return (
    <>
      <Head>
        <title>Contai Comunidade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <AuthLayout title="Que bom te ver, seja bem vind@ de volta!">
        <Typography.Text as="h3" size="body1" weight="bold" color="title">
          Preencha os campos para acessar sua conta
        </Typography.Text>
      </AuthLayout>
    </>
  );
}
